version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - internal_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://root:password@mongodb:27017/alzheimer_db?authSource=admin
    depends_on:
      - mongodb
    networks:
      - internal_network
    volumes:
      - ./backend:/app  # <-- Monta el código local directamente en el contenedor
      - /app/__pycache__/
      - ./CNN_Categorical_Crossentropy.h5:/app/CNN_Categorical_Crossentropy.h5


networks:
  internal_network:
    driver: bridge
